# -*- coding: mbcs -*-
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.Model(name='Model-1')
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='web', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='flange', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].ConstrainedSketch(name='geometry', sheetSize=4.0)
mdb.models['Model-1'].sketches['geometry'].Line(point1=(-1.5, 0.0), point2=(
    1.5, 0.0))
mdb.models['Model-1'].sketches['geometry'].Line(point1=(-0.9, 0.0), point2=(
    -0.9, 0.125))
mdb.models['Model-1'].sketches['geometry'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['geometry'].geometry.findAt((
    0.0, 0.0), ))
mdb.models['Model-1'].sketches['geometry'].Line(point1=(-0.95, 0.125), point2=(
    -0.85, 0.125))
mdb.models['Model-1'].sketches['geometry'].HorizontalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['geometry'].geometry.findAt((
    0.0, 0.0), ))
mdb.models['Model-1'].sketches['geometry'].Line(point1=(-0.3, 0.0), point2=(
    -0.3, 0.125))
mdb.models['Model-1'].sketches['geometry'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['geometry'].geometry.findAt((
    -0.9, 0.0625), ))
mdb.models['Model-1'].sketches['geometry'].Line(point1=(-0.35, 0.125), point2=(
    -0.25, 0.125))
mdb.models['Model-1'].sketches['geometry'].HorizontalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['geometry'].geometry.findAt((
    -0.9, 0.0625), ))
mdb.models['Model-1'].sketches['geometry'].Line(point1=(0.3, 0.0), point2=(0.3, 
    0.125))
mdb.models['Model-1'].sketches['geometry'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['geometry'].geometry.findAt((
    -0.9, 0.125), ))
mdb.models['Model-1'].sketches['geometry'].Line(point1=(0.25, 0.125), point2=(
    0.35, 0.125))
mdb.models['Model-1'].sketches['geometry'].HorizontalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['geometry'].geometry.findAt((
    -0.9, 0.125), ))
mdb.models['Model-1'].sketches['geometry'].Line(point1=(0.9, 0.0), point2=(0.9, 
    0.125))
mdb.models['Model-1'].sketches['geometry'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['geometry'].geometry.findAt((
    -0.3, 0.0625), ))
mdb.models['Model-1'].sketches['geometry'].Line(point1=(0.85, 0.125), point2=(
    0.95, 0.125))
mdb.models['Model-1'].sketches['geometry'].HorizontalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['geometry'].geometry.findAt((
    -0.3, 0.0625), ))
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['plate'].BaseShellExtrude(depth=3.0, sketch=
    mdb.models['Model-1'].sketches['geometry'])
del mdb.models['Model-1'].sketches['geometry']
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name=
    'cross-section', type=DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.0, 
    0.0), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.95, 0.125), 
    point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.0, 
    0.0), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.3, 0.0), 
    point2=(-0.3, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.35, 0.125), 
    point2=(-0.25, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(0.3, 0.0), 
    point2=(0.3, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(0.25, 0.125), 
    point2=(0.35, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(0.9, 0.0), 
    point2=(0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(0.85, 0.125), 
    point2=(0.95, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
del mdb.models['Model-1']
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.0, 
    0.0), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.95, 0.125), 
    point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.0, 
    0.0), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.3, 0.0), 
    point2=(-0.3, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.35, 0.125), 
    point2=(-0.25, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(0.3, 0.0), 
    point2=(0.3, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(0.25, 0.125), 
    point2=(0.35, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(0.9, 0.0), 
    point2=(0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(0.85, 0.125), 
    point2=(0.95, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((0.0, 0.0, 
    1.5), )), name='PlateFace')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    [mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.9, 
    0.083333, 2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.9, 0.083333, 
    2.0), (1.0, 0.0, 0.0))], name='WebFaces')
#* Feature creation failed.
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((1.1, 0.0, 
    1.0), (0.0, -1.0, 0.0)), ((0.7, 0.0, 2.0), (0.0, -1.0, 0.0)), ((-1.1, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ((-0.1, 0.0, 1.0), (0.0, -1.0, 0.0)), ((-0.5, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ), name='PlateFace')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    [mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.9, 
    0.083333, 2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.9, 0.083333, 
    2.0), (1.0, 0.0, 0.0))], name='WebFaces')
#* Feature creation failed.
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.models['Parametric-Panel'].parts['plate'].Set(edges=
    [mdb.models['Parametric-Panel'].parts['plate'].edges.findAt((-1.5, 0.0, 
    0.75), ), mdb.models['Parametric-Panel'].parts['plate'].edges.findAt((1.5, 
    0.0, 0.75), )], name='PlateFace')
#* Feature creation failed.
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
#* TypeError: keyword error on xMax
#* TypeError: keyword error on xMax
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((1.1, 0.0, 
    1.0), (0.0, -1.0, 0.0)), ((0.7, 0.0, 2.0), (0.0, -1.0, 0.0)), ((-1.1, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ((-0.1, 0.0, 1.0), (0.0, -1.0, 0.0)), ((-0.5, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ), name='PlateFace')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((1.1, 0.0, 
    1.0), (0.0, -1.0, 0.0)), ((0.7, 0.0, 2.0), (0.0, -1.0, 0.0)), ((-1.1, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ((-0.1, 0.0, 1.0), (0.0, -1.0, 0.0)), ((-0.5, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ((-0.9, 0.083333, 2.0), (1.0, 0.0, 0.0)), ((
    -0.916667, 0.125, 2.0), (0.0, -1.0, 0.0)), ((-0.883333, 0.125, 1.0), (0.0, 
    -1.0, 0.0)), ((0.3, 0.083333, 2.0), (1.0, 0.0, 0.0)), ((0.283333, 0.125, 
    2.0), (0.0, -1.0, 0.0)), ((0.316667, 0.125, 1.0), (0.0, -1.0, 0.0)), ((0.9, 
    0.083333, 2.0), (1.0, 0.0, 0.0)), ((0.883333, 0.125, 2.0), (0.0, -1.0, 
    0.0)), ((0.916667, 0.125, 1.0), (0.0, -1.0, 0.0)), ((-0.3, 0.083333, 2.0), 
    (1.0, 0.0, 0.0)), ((-0.316667, 0.125, 2.0), (0.0, -1.0, 0.0)), ((-0.283333, 
    0.125, 1.0), (0.0, -1.0, 0.0)), ), name='FlangeFaces')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    [mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.9, 
    0.083333, 2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.9, 0.083333, 
    2.0), (1.0, 0.0, 0.0))], name='WebFaces')
#* Feature creation failed.
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((1.1, 0.0, 
    1.0), (0.0, -1.0, 0.0)), ((0.7, 0.0, 2.0), (0.0, -1.0, 0.0)), ((-1.1, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ((-0.1, 0.0, 1.0), (0.0, -1.0, 0.0)), ((-0.5, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ), name='PlateFace')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((-0.916667, 
    0.125, 2.0), (0.0, -1.0, 0.0)), ((-0.883333, 0.125, 1.0), (0.0, -1.0, 
    0.0)), ((0.283333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.316667, 0.125, 1.0), 
    (0.0, -1.0, 0.0)), ((0.883333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.916667, 
    0.125, 1.0), (0.0, -1.0, 0.0)), ((-0.316667, 0.125, 2.0), (0.0, -1.0, 
    0.0)), ((-0.283333, 0.125, 1.0), (0.0, -1.0, 0.0)), ), name='FlangeFaces')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    [mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.9, 
    0.083333, 2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.9, 0.083333, 
    2.0), (1.0, 0.0, 0.0))], name='WebFaces')
#* Feature creation failed.
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((1.1, 0.0, 
    1.0), (0.0, -1.0, 0.0)), ((0.7, 0.0, 2.0), (0.0, -1.0, 0.0)), ((-1.1, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ((-0.1, 0.0, 1.0), (0.0, -1.0, 0.0)), ((-0.5, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ), name='PlateFace')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((-0.916667, 
    0.125, 2.0), (0.0, -1.0, 0.0)), ((-0.883333, 0.125, 1.0), (0.0, -1.0, 
    0.0)), ((0.283333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.316667, 0.125, 1.0), 
    (0.0, -1.0, 0.0)), ((0.883333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.916667, 
    0.125, 1.0), (0.0, -1.0, 0.0)), ((-0.316667, 0.125, 2.0), (0.0, -1.0, 
    0.0)), ((-0.283333, 0.125, 1.0), (0.0, -1.0, 0.0)), ), name='FlangeFaces')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=(
    [mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.9, 
    0.083333, 2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.9, 0.083333, 
    2.0), (1.0, 0.0, 0.0))], ), name='WebFaces')
#* Feature creation failed.
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((1.1, 0.0, 
    1.0), (0.0, -1.0, 0.0)), ((0.7, 0.0, 2.0), (0.0, -1.0, 0.0)), ((-1.1, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ((-0.1, 0.0, 1.0), (0.0, -1.0, 0.0)), ((-0.5, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ), name='PlateFace')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((-0.916667, 
    0.125, 2.0), (0.0, -1.0, 0.0)), ((-0.883333, 0.125, 1.0), (0.0, -1.0, 
    0.0)), ((0.283333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.316667, 0.125, 1.0), 
    (0.0, -1.0, 0.0)), ((0.883333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.916667, 
    0.125, 1.0), (0.0, -1.0, 0.0)), ((-0.316667, 0.125, 2.0), (0.0, -1.0, 
    0.0)), ((-0.283333, 0.125, 1.0), (0.0, -1.0, 0.0)), ), name='FlangeFaces')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    [mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.9, 
    0.083333, 2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.9, 0.083333, 
    2.0), (1.0, 0.0, 0.0))], name='WebFaces')
#* Feature creation failed.
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((1.1, 0.0, 
    1.0), (0.0, -1.0, 0.0)), ((0.7, 0.0, 2.0), (0.0, -1.0, 0.0)), ((-1.1, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ((-0.1, 0.0, 1.0), (0.0, -1.0, 0.0)), ((-0.5, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ), name='PlateFace')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((-0.916667, 
    0.125, 2.0), (0.0, -1.0, 0.0)), ((-0.883333, 0.125, 1.0), (0.0, -1.0, 
    0.0)), ((0.283333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.316667, 0.125, 1.0), 
    (0.0, -1.0, 0.0)), ((0.883333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.916667, 
    0.125, 1.0), (0.0, -1.0, 0.0)), ((-0.316667, 0.125, 2.0), (0.0, -1.0, 
    0.0)), ((-0.283333, 0.125, 1.0), (0.0, -1.0, 0.0)), ), name='FlangeFaces')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    [mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.9, 
    0.083333, 2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.9, 0.083333, 
    2.0), (1.0, 0.0, 0.0))], name='WebFaces')
#* Feature creation failed.
mdb.Model(name='Parametric-Panel')
mdb.models['Parametric-Panel'].ConstrainedSketch(name='geometry', sheetSize=
    4.0)
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-1.5, 0.0), 
    point2=(1.5, 0.0))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(-0.9, 0.0), 
    point2=(-0.9, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.9500000000000001, 0.125), point2=(-0.85, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.9, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.30000000000000004, 0.0), point2=(-0.30000000000000004, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((-0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    -0.35000000000000003, 0.125), point2=(-0.25000000000000006, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (-0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.29999999999999993, 0.0), point2=(0.29999999999999993, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.3, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.24999999999999994, 0.125), point2=(0.3499999999999999, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.3, 0.125), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8999999999999998, 0.0), point2=(0.8999999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].VerticalConstraint(entity=
    mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt((0.9, 
    0.0625), ))
mdb.models['Parametric-Panel'].sketches['geometry'].Line(point1=(
    0.8499999999999998, 0.125), point2=(0.9499999999999998, 0.125))
mdb.models['Parametric-Panel'].sketches['geometry'].HorizontalConstraint(
    entity=mdb.models['Parametric-Panel'].sketches['geometry'].geometry.findAt(
    (0.9, 0.125), ))
mdb.models['Parametric-Panel'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['Parametric-Panel'].parts['plate'].BaseShellExtrude(depth=3.0, 
    sketch=mdb.models['Parametric-Panel'].sketches['geometry'])
del mdb.models['Parametric-Panel'].sketches['geometry']
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((1.1, 0.0, 
    1.0), (0.0, -1.0, 0.0)), ((0.7, 0.0, 2.0), (0.0, -1.0, 0.0)), ((-1.1, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ((-0.1, 0.0, 1.0), (0.0, -1.0, 0.0)), ((-0.5, 0.0, 
    2.0), (0.0, -1.0, 0.0)), ), name='PlateFace')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt(((-0.916667, 
    0.125, 2.0), (0.0, -1.0, 0.0)), ((-0.883333, 0.125, 1.0), (0.0, -1.0, 
    0.0)), ((0.283333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.316667, 0.125, 1.0), 
    (0.0, -1.0, 0.0)), ((0.883333, 0.125, 2.0), (0.0, -1.0, 0.0)), ((0.916667, 
    0.125, 1.0), (0.0, -1.0, 0.0)), ((-0.316667, 0.125, 2.0), (0.0, -1.0, 
    0.0)), ((-0.283333, 0.125, 1.0), (0.0, -1.0, 0.0)), ), name='FlangeFaces')
mdb.models['Parametric-Panel'].parts['plate'].Set(faces=(
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.9, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((-0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.3, 0.083333, 
    2.0), (1.0, 0.0, 0.0)), 
    mdb.models['Parametric-Panel'].parts['plate'].faces.findAt((0.9, 0.083333, 
    2.0), (1.0, 0.0, 0.0))), name='WebFaces')
#* Feature creation failed.
